# Generated by Django 2.2.5 on 2020-01-08 21:20

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('director', models.CharField(max_length=60)),
                ('studio', models.CharField(max_length=30)),
                ('platform', models.CharField(max_length=30)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
